In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
%matplotlib inline
import random
from sklearn.preprocessing import LabelEncoder

In [2]:
Data_df = pd.read_csv("train-Copy1.csv")

/home/rakesh0035123/anaconda3/envs/MyEnvi/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
Data_df.shape

(8921483, 83)

In [4]:
Data_df[['MachineIdentifier']].shape

(8921483, 1)

In [5]:
id_df = Data_df[['MachineIdentifier']]

In [6]:
display(id_df)

                        MachineIdentifier
0        0000028988387b115f69f31a3bf04f09
1        000007535c3f730efa9ea0b7ef1bd645
2        000007905a28d863f6d0d597892cd692
3        00000b11598a75ea8ba1beea8459149f
4        000014a5f00daa18e76b81417eeb99fc
5        000016191b897145d069102325cab760
6        0000161e8abf8d8b89c5ab8787fd712b
7        000019515bc8f95851aff6de873405e8
8        00001a027a0ab970c408182df8484fce
9        00001a18d69bb60bda9779408dcf02ac
10       00001b3b3cf8c8c079a272ce51031753
11       00001b924fcc6922321cfadbafd8a91a
12       00001f26e9e5775277d6231fc6ac9e70
13       000024872c81cf03fa862aa8f99e0984
14       0000258d2b847c7549150cfec6464473
15       000027c68b89acb49d4017763b043449
16       000028150912f45b1dc667164de489ef
17       00002a7fd74f9ca4a59a679a7cc80388
18       00002b7454f06444e8d9f6083d8a9ebd
19       00002c6cccecdef94aaa557d0458ab8a
20       0000309dcbba938f8aa7ee5a0204119d
21       000033565d8f7a3029afd1d6c4c465e9
22       0000378813e163d00d5e5f7e0a12b6d9
23       000037f84e21c83328ba6963cdac497b
24       000038f24a1ee98931456b3e49f7934b
25       000039104d7f42c15fdc0d1bcb9d4b4a
26       000039c280a86ff549f7f3526e918ae4
27       00003ad63e561a25415551cd47d426d5
28       00003e5e679ccfe7a13e953c47dd584f
29       0000422df51e713f82b98e04cb883cb5
...                                   ...
8921453  ffffbebef5e10a1dc19d7cbe328f2364
8921454  ffffbfe116b4ea54758aac8b691eddce
8921455  ffffc47e67eb2bdaf37568a3b15dc155
8921456  ffffc5dde89da955e53776ccda71e538
8921457  ffffc5f7e831e9af161f44643ce62ccb
8921458  ffffc701b233caac43f7ee4566481270
8921459  ffffc861fe5059efce858bee3913281b
8921460  ffffcb102f3b412425af4abe59b1d354
8921461  ffffcbbb01e0ea9a561138e90ee2a17e
8921462  ffffd06bbab3c50ea7024690f9552b72
8921463  ffffd173ebdb55a39b65ceef5db64f55
8921464  ffffd19c65f9e53c885ba934dc8c8144
8921465  ffffd4fb35ab1da9b6555019e7201657
8921466  ffffe0072c046e41553145bd8f27e30c
8921467  ffffe20be42c95403f0187252d62ce5a
8921468  ffffe3ad635d697ab880950735bf7281
8921469  ffffe3c5bd9dfe03872c2a9c398b5c39
8921470  ffffe403c281f7df29569c3f50a17969
8921471  ffffe845668e2b132716cbd523352e76
8921472  ffffe84f7fb96a120e171620c9a6d8b5
8921473  ffffe94d10ed6d3c0c69264d7c7f6792
8921474  ffffe96540e514a48dcd54ddfecf9d02
8921475  ffffeb276b93e6e2608bba3f3d8bc9da
8921476  ffffec21b3433f5f2752ed8677935ad0
8921477  ffffedd8bc7e8de37f352f3b90694f52
8921478  ffffedfe8fcc46e6d36ab39953589fee
8921479  ffffef606490b2970873ec0a27ebd24b
8921480  fffff8a40070d2d8379bb7fa2ed2fa66
8921481  fffffbbaaf5969ae4b93e7f3f6d7132f
8921482  ffffff75ba4f33d938ccfdb148b8ea16

[8921483 rows x 1 columns]

In [7]:
id_df.shape

(8921483, 1)

In [8]:
id_df.to_csv('id_data.csv', index=False)

In [4]:
Data_df = Data_df.select_dtypes(include=('int64','float64'))
display(Data_df.head(4))

,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,AVProductsInstalled,AVProductsEnabled,HasTpm,CountryIdentifier,CityIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0,7.0,0,NaN,53447.0,1.0,1.0,1,29,128035.0,...,36144.0,0,NaN,0.0,0,0,0.0,0.0,10.0,0
1,0,7.0,0,NaN,53447.0,1.0,1.0,1,93,1482.0,...,57858.0,0,NaN,0.0,0,0,0.0,0.0,8.0,0
2,0,7.0,0,NaN,53447.0,1.0,1.0,1,86,153579.0,...,52682.0,0,NaN,0.0,0,0,0.0,0.0,3.0,0
3,0,7.0,0,NaN,53447.0,1.0,1.0,1,88,20710.0,...,20050.0,0,NaN,0.0,0,0,0.0,0.0,3.0,1

In [5]:
Data_df.isnull().sum()

IsBeta                                                     0
RtpStateBitfield                                       32318
IsSxsPassiveMode                                           0
DefaultBrowsersIdentifier                            8488045
AVProductStatesIdentifier                              36221
AVProductsInstalled                                    36221
AVProductsEnabled                                      36221
HasTpm                                                     0
CountryIdentifier                                          0
CityIdentifier                                        325409
OrganizationIdentifier                               2751518
GeoNameIdentifier                                        213
LocaleEnglishNameIdentifier                                0
OsBuild                                                    0
OsSuite                                                    0
IsProtected                                            36044
AutoSampleOptIn                                            0
SMode                                                 537759
IeVerIdentifier                                        58894
Firewall                                               91350
UacLuaenable                                           10838
Census_OEMNameIdentifier                               95478
Census_OEMModelIdentifier                             102233
Census_ProcessorCoreCount                              41306
Census_ProcessorManufacturerIdentifier                 41313
Census_ProcessorModelIdentifier                        41343
Census_PrimaryDiskTotalCapacity                        53016
Census_SystemVolumeTotalCapacity                       53002
Census_HasOpticalDiskDrive                                 0
Census_TotalPhysicalRAM                                80533
Census_InternalPrimaryDiagonalDisplaySizeInInches      47134
Census_InternalPrimaryDisplayResolutionHorizontal      46986
Census_InternalPrimaryDisplayResolutionVertical        46986
Census_InternalBatteryNumberOfCharges                 268755
Census_OSBuildNumber                                       0
Census_OSBuildRevision                                     0
Census_OSInstallLanguageIdentifier                     60084
Census_OSUILocaleIdentifier                                0
Census_IsPortableOperatingSystem                           0
Census_IsFlightingInternal                           7408759
Census_IsFlightsDisabled                              160523
Census_ThresholdOptIn                                5667325
Census_FirmwareManufacturerIdentifier                 183257
Census_FirmwareVersionIdentifier                      160133
Census_IsSecureBootEnabled                                 0
Census_IsWIMBootEnabled                              5659703
Census_IsVirtualDevice                                 15953
Census_IsTouchEnabled                                      0
Census_IsPenCapable                                        0
Census_IsAlwaysOnAlwaysConnectedCapable                71343
Wdft_IsGamer                                          303451
Wdft_RegionIdentifier                                 303451
HasDetections                                              0
dtype: int64

In [6]:
Data_df.head()

,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,AVProductsInstalled,AVProductsEnabled,HasTpm,CountryIdentifier,CityIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0,7.0,0,NaN,53447.0,1.0,1.0,1,29,128035.0,...,36144.0,0,NaN,0.0,0,0,0.0,0.0,10.0,0
1,0,7.0,0,NaN,53447.0,1.0,1.0,1,93,1482.0,...,57858.0,0,NaN,0.0,0,0,0.0,0.0,8.0,0
2,0,7.0,0,NaN,53447.0,1.0,1.0,1,86,153579.0,...,52682.0,0,NaN,0.0,0,0,0.0,0.0,3.0,0
3,0,7.0,0,NaN,53447.0,1.0,1.0,1,88,20710.0,...,20050.0,0,NaN,0.0,0,0,0.0,0.0,3.0,1
4,0,7.0,0,NaN,53447.0,1.0,1.0,1,18,37376.0,...,19844.0,0,0.0,0.0,0,0,0.0,0.0,1.0,1

In [15]:
Data_df = Data_df.fillna(value="N")

In [18]:
display(Data_df.head())

,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,AVProductsInstalled,AVProductsEnabled,HasTpm,CountryIdentifier,CityIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0,7,0,N,53447,1,1,1,29,128035,...,36144,0,N,0,0,0,0,0,10,0
1,0,7,0,N,53447,1,1,1,93,1482,...,57858,0,N,0,0,0,0,0,8,0
2,0,7,0,N,53447,1,1,1,86,153579,...,52682,0,N,0,0,0,0,0,3,0
3,0,7,0,N,53447,1,1,1,88,20710,...,20050,0,N,0,0,0,0,0,3,1
4,0,7,0,N,53447,1,1,1,18,37376,...,19844,0,0,0,0,0,0,0,1,1

In [17]:
display(Data_df['DefaultBrowsersIdentifier'][Data_df['DefaultBrowsersIdentifier'] == 'N' ])

0          N
1          N
2          N
3          N
4          N
5          N
6          N
7          N
8          N
9          N
10         N
11         N
12         N
13         N
14         N
15         N
16         N
17         N
18         N
19         N
20         N
21         N
22         N
23         N
24         N
26         N
27         N
28         N
29         N
30         N
          ..
8921450    N
8921451    N
8921453    N
8921454    N
8921455    N
8921456    N
8921457    N
8921458    N
8921460    N
8921461    N
8921462    N
8921463    N
8921464    N
8921465    N
8921466    N
8921467    N
8921468    N
8921469    N
8921470    N
8921471    N
8921472    N
8921473    N
8921474    N
8921475    N
8921476    N
8921477    N
8921478    N
8921480    N
8921481    N
8921482    N
Name: DefaultBrowsersIdentifier, Length: 8488045, dtype: object

In [19]:
Columns = (['DefaultBrowsersIdentifier','CityIdentifier','AVProductStatesIdentifier' ,'OrganizationIdentifier','GeoNameIdentifier','IeVerIdentifier','Census_OEMNameIdentifier',
            'Census_OEMModelIdentifier','Census_ProcessorCoreCount','Census_ProcessorModelIdentifier','Census_PrimaryDiskTotalCapacity','Census_SystemVolumeTotalCapacity',
            'Census_TotalPhysicalRAM','Census_InternalPrimaryDiagonalDisplaySizeInInches','Census_InternalPrimaryDisplayResolutionHorizontal',
            'Census_InternalPrimaryDisplayResolutionVertical','Census_InternalBatteryNumberOfCharges','Census_OSInstallLanguageIdentifier',
            'Census_FirmwareManufacturerIdentifier','Census_FirmwareVersionIdentifier'])

In [20]:
for col in Columns:
    print(col)
#     Data1_df = Data_df[Data_df[col]!='Not Given']
    Temp_df = Data_df[Data_df[col]!='N'][[col,'HasDetections']].groupby([col], as_index=False).mean().sort_values(by='HasDetections', ascending=False)
    p25 = np.percentile(Temp_df['HasDetections'], 25)
    p40 = np.percentile(Temp_df['HasDetections'], 40)
    p70 = np.percentile(Temp_df['HasDetections'], 70)
    Temp_combine1 = [Temp_df]
    for duplicate_df in Temp_combine1 :
#         display(b)
#         duplicate_df.loc[ duplicate_df.HasDetections == 'Not Given', col + '_catg'] = 0
        duplicate_df.loc[ duplicate_df.HasDetections <= p25,col + '_catg'] = 1
        duplicate_df.loc[(duplicate_df.HasDetections > p25) & (duplicate_df.HasDetections <= p40),col + '_catg'] = 2
        duplicate_df.loc[(duplicate_df.HasDetections > p40) & (duplicate_df.HasDetections <= p70),col + '_catg'] = 3
        duplicate_df.loc[ duplicate_df.HasDetections > p70,col + '_catg'] = 4

    
    display(duplicate_df.head())  
    Data_df[col] = Data_df[col].astype(str)
#     test_numerics_df[col] = test_numerics_df[col].astype(str)
#     print(train_numerics_df.shape,test_numerics_df.shape)
    duplicate_df= duplicate_df.astype(str)
    duplicate_df = duplicate_df.drop('HasDetections',axis=1)
    Data_df = Data_df.merge(duplicate_df,on=col,how='left')
#     test_numerics_df = test_numerics_df.merge(duplicate_df,on=col,how='left')
#     duplicate_df.to_csv(col + '_catg.csv', index=False)

DefaultBrowsersIdentifier

      DefaultBrowsersIdentifier  HasDetections  DefaultBrowsersIdentifier_catg
2016                     3213.0            1.0                             4.0
493                       768.0            1.0                             4.0
496                       772.0            1.0                             4.0
1368                     2187.0            1.0                             4.0
1365                     2180.0            1.0                             4.0

CityIdentifier

       CityIdentifier  HasDetections  CityIdentifier_catg
72242        113225.0            1.0                  4.0
36854         57651.0            1.0                  4.0
13771         21284.0            1.0                  4.0
13770         21282.0            1.0                  4.0
36848         57642.0            1.0                  4.0

AVProductStatesIdentifier

,AVProductStatesIdentifier,HasDetections,AVProductStatesIdentifier_catg
0,3.0,1.0,4.0
13105,31290.0,1.0,4.0
26380,64314.0,1.0,4.0
13116,31316.0,1.0,4.0
26382,64316.0,1.0,4.0

OrganizationIdentifier

    OrganizationIdentifier  HasDetections  OrganizationIdentifier_catg
34                    38.0       1.000000                          4.0
14                    17.0       1.000000                          4.0
46                    50.0       0.609907                          4.0
17                    20.0       0.597814                          4.0
7                      8.0       0.576763                          4.0

GeoNameIdentifier

     GeoNameIdentifier  HasDetections  GeoNameIdentifier_catg
88                92.0       1.000000                     4.0
127              132.0       1.000000                     4.0
275              280.0       0.833333                     4.0
254              259.0       0.818182                     4.0
164              169.0       0.800000                     4.0

IeVerIdentifier

     IeVerIdentifier  HasDetections  IeVerIdentifier_catg
159            213.0            1.0                   4.0
16              22.0            1.0                   4.0
101            141.0            1.0                   4.0
262            379.0            1.0                   4.0
259            376.0            1.0                   4.0

Census_OEMNameIdentifier

      Census_OEMNameIdentifier  HasDetections  Census_OEMNameIdentifier_catg
1916                    3037.0            1.0                            4.0
1521                    2411.0            1.0                            4.0
3396                    5357.0            1.0                            4.0
485                      877.0            1.0                            4.0
487                      880.0            1.0                            4.0

Census_OEMModelIdentifier

,Census_OEMModelIdentifier,HasDetections,Census_OEMModelIdentifier_catg
66171,139265.0,1.0,4.0
75590,157429.0,1.0,4.0
75612,157503.0,1.0,4.0
75606,157489.0,1.0,4.0
31220,65084.0,1.0,4.0

Census_ProcessorCoreCount

    Census_ProcessorCoreCount  HasDetections  Census_ProcessorCoreCount_catg
44                      192.0          1.000                             4.0
41                      120.0          1.000                             4.0
28                       46.0          1.000                             4.0
20                       25.0          1.000                             4.0
27                       44.0          0.625                             4.0

Census_ProcessorModelIdentifier

,Census_ProcessorModelIdentifier,HasDetections,Census_ProcessorModelIdentifier_catg
3427,4479.0,1.0,4.0
3013,3888.0,1.0,4.0
957,1197.0,1.0,4.0
954,1189.0,1.0,4.0
941,1175.0,1.0,4.0

Census_PrimaryDiskTotalCapacity

,Census_PrimaryDiskTotalCapacity,HasDetections,Census_PrimaryDiskTotalCapacity_catg
4007,445676.0,1.0,4.0
3634,286171.0,1.0,4.0
1121,51709.0,1.0,4.0
3642,286995.0,1.0,4.0
3644,287677.0,1.0,4.0

Census_SystemVolumeTotalCapacity

,Census_SystemVolumeTotalCapacity,HasDetections,Census_SystemVolumeTotalCapacity_catg
268424,326040.0,1.0,4.0
287399,358010.0,1.0,4.0
287361,357956.0,1.0,4.0
287364,357959.0,1.0,4.0
287366,357961.0,1.0,4.0

Census_TotalPhysicalRAM

      Census_TotalPhysicalRAM  HasDetections  Census_TotalPhysicalRAM_catg
1723                   5117.0            1.0                           4.0
2843                  12095.0            1.0                           4.0
2866                  12194.0            1.0                           4.0
2863                  12186.0            1.0                           4.0
937                    3162.0            1.0                           4.0

Census_InternalPrimaryDiagonalDisplaySizeInInches

,Census_InternalPrimaryDiagonalDisplaySizeInInches,HasDetections,Census_InternalPrimaryDiagonalDisplaySizeInInches_catg
756,101.5,1.0,4.0
603,65.9,1.0,4.0
589,64.4,1.0,4.0
583,63.8,1.0,4.0
579,63.3,1.0,4.0

Census_InternalPrimaryDisplayResolutionHorizontal

,Census_InternalPrimaryDisplayResolutionHorizontal,HasDetections,Census_InternalPrimaryDisplayResolutionHorizontal_catg
174,875.0,1.0,4.0
1827,3198.0,1.0,4.0
1864,3326.0,1.0,4.0
1863,3325.0,1.0,4.0
1862,3314.0,1.0,4.0

Census_InternalPrimaryDisplayResolutionVertical

MemoryError:

In [21]:
display(Data_df.head())

,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,AVProductsInstalled,AVProductsEnabled,HasTpm,CountryIdentifier,CityIdentifier,...,IeVerIdentifier_catg,Census_OEMNameIdentifier_catg,Census_OEMModelIdentifier_catg,Census_ProcessorCoreCount_catg,Census_ProcessorModelIdentifier_catg,Census_PrimaryDiskTotalCapacity_catg,Census_SystemVolumeTotalCapacity_catg,Census_TotalPhysicalRAM_catg,Census_InternalPrimaryDiagonalDisplaySizeInInches_catg,Census_InternalPrimaryDisplayResolutionHorizontal_catg
0,0,7,0,N,53447.0,1,1,1,29,128035.0,...,4.0,4.0,3.0,4.0,4.0,4.0,3.0,4.0,3.0,4.0
1,0,7,0,N,53447.0,1,1,1,93,1482.0,...,4.0,4.0,1.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0
2,0,7,0,N,53447.0,1,1,1,86,153579.0,...,4.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0,4.0,4.0
3,0,7,0,N,53447.0,1,1,1,88,20710.0,...,4.0,4.0,3.0,4.0,4.0,3.0,2.0,4.0,4.0,4.0
4,0,7,0,N,53447.0,1,1,1,18,37376.0,...,4.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0

In [23]:
Data_df.to_csv('num_half(data).csv', index=False)